#
# Copyright 2021-2025 Software Radio Systems Limited
#
# This file is part of srsRAN
#
# srsRAN is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# srsRAN is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# A copy of the GNU Affero General Public License can be found in
# the LICENSE file in the top-level directory of this distribution
# and at http://www.gnu.org/licenses/.
#

services:
  5gc:
    container_name: open5gs_5gc
    image: akhil15935/open5gs-5gc:latest
    env_file:
      - ${OPEN_5GS_ENV_FILE:-open5gs/open5gs.env}
    privileged: true
    ports:
      - "9999:9999/tcp"
    # Uncomment port to use the 5gc from outside the docker network
    #  - "38412:38412/sctp"
    #  - "2152:2152/udp"
    command: 5gc -c open5gs-5gc.yml
    healthcheck:
      test: [ "CMD-SHELL", "nc -z 127.0.0.20 7777" ]
      interval: 3s
      timeout: 1s
      retries: 60
    networks:
      ran:
        ipv4_address: ${OPEN5GS_IP:-10.53.1.2}

  cu:
    container_name: srsran_cu
    image: srsran/gnb
    privileged: true
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - CAP_SYS_PTRACE
    volumes:
      # Access USB to use some SDRs
      - /dev/bus/usb/:/dev/bus/usb/
      # Sharing images between the host and the pod.
      # It's also possible to download the images inside the pod
      - /usr/share/uhd/images:/usr/share/uhd/images
      # Save logs and more into gnb-storage
      - gnb-storage:/tmp
      - ./cu_config.yml:/cu_config.yml
      - ./cu_logs:/tmp
    networks:
      ran:
        ipv4_address: ${GNB_IP:-10.53.1.4}
      ue:
        ipv4_address: 10.53.10.4
      metrics:
        ipv4_address: 10.53.2.7
    # Start GNB container after 5gc is up and running
    depends_on:
      5gc:
        condition: service_healthy
   # Command to run into the final container
    command: srscu -c /cu_config.yml

  du:
    container_name: srsran_du
    image: srsran/gnb
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_NICE
      - CAP_SYS_PTRACE
    volumes:
      # Access USB to use some SDRs
      - /dev/bus/usb/:/dev/bus/usb/
      # Sharing images between the host and the pod.
      # It's also possible to download the images inside the pod
      - /usr/share/uhd/images:/usr/share/uhd/images
      # Save logs and more into gnb-storage
      - gnb-storage:/tmp
      - ./du_config.yml:/du_config.yml
      - ./du_logs:/tmp
    networks:
      ran:
        ipv4_address: ${GNB_IP:-10.53.1.5}
      ue:
        ipv4_address: 10.53.10.5
      metrics:
        ipv4_address: 10.53.2.8
    # Start GNB container after 5gc is up and running
    depends_on:
      5gc:
        condition: service_healthy
    # Command to run into the final container
    command: srsdu -c /du_config.yml
    # command: sleep infinity

  gnb:
    container_name: srsran_gnb
    # Build info
    image: srsran/gnb
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        OS_VERSION: "24.04"
    # privileged mode is requred only for accessing usb devices
    privileged: true
    # Extra capabilities always required
    cap_add:
      - SYS_NICE
      - CAP_SYS_PTRACE
    volumes:
      # Access USB to use some SDRs
      - /dev/bus/usb/:/dev/bus/usb/
      # Sharing images between the host and the pod.
      # It's also possible to download the images inside the pod
      - /usr/share/uhd/images:/usr/share/uhd/images
      # Save logs and more into gnb-storage
      - gnb-storage:/tmp
      - ./gnb_config.yml:/gnb_config.yml
      - ./logs:/tmp
    # It creates a file/folder into /config_name inside the container
    # Its content would be the value of the file used to create the config
    configs:
      - gnb_config.yml
    # Customize your desired network mode.
    # current netowrk configuration creastes a private netwoek with both containers attached
    # An alterantive would be `network: host"`. That would expose your host network into the container. It's the easiest to use if the 5gc is not in your PC
    networks:
      ran:
        ipv4_address: ${GNB_IP:-10.53.1.3}
      metrics:
        ipv4_address: 10.53.2.3
    # Start GNB container after 5gc is up and running
    depends_on:
      5gc:
        condition: service_healthy
    # Command to run into the final container
    command: gnb -c /gnb_config.yml 

  srsue:
    image: akhil15935/srsue:split_8
    container_name: ue1
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    depends_on:
      - gnb
    volumes:
      - ./ue1.conf:/ue.conf
    environment:
      - LD_LIBRARY_PATH=/srsran/lib/src/phy/rf/
    networks:
      ran:
        ipv4_address: 10.53.1.10
    command: /srsran/srsue/src/srsue /ue.conf
  srsue1:
    image: ue
    container_name: ue2
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    depends_on:
      - cu
      - du
    volumes:
      - ./ue2.conf:/ue.conf
    environment:
      - LD_LIBRARY_PATH=/srsran/lib/src/phy/rf/
    networks:
      ue:
        ipv4_address: 10.53.10.20
    command: srsue /ue.conf
  metrics-server:
    container_name: metrics_server
    image: srsran/metrics_server
    build:
      context: metrics_server
    environment:
      - PORT=${METRICS_SERVER_PORT}
      - BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
      - TESTBED=default
      - URL=http://${DOCKER_INFLUXDB_INIT_HOST}:${DOCKER_INFLUXDB_INIT_PORT}
      - ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
    ports:
      - 55555:${METRICS_SERVER_PORT}/udp
    networks:
      metrics:
        ipv4_address: 10.53.2.4

  influxdb:
    container_name: influxdb
    image: influxdb:${DOCKER_INFLUXDB_VERSION}
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    restart: on-failure:10
    # Uncomment port section to access InfluxDB from outside the docker network
    # ports:
    #   - 8086:${DOCKER_INFLUXDB_INIT_PORT}
    networks:
      metrics:
        ipv4_address: 10.53.2.5

  grafana:
    container_name: grafana
    image: srsran/grafana
    build:
      context: grafana
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    env_file:
      - .env
    depends_on:
      - influxdb
      - metrics-server
    ports:
      - 3300:${GRAFANA_PORT}
    networks:
      metrics:
        ipv4_address: 10.53.2.6

configs:
  gnb_config.yml:
    file: ${GNB_CONFIG_PATH:-../configs/gnb_rf_b200_tdd_n78_20mhz.yml} # Path to your desired config file

volumes:
  gnb-storage:
  grafana-storage:
  influxdb-storage:

networks:
  ran:
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 10.53.1.0/24
  ue:
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 10.53.10.0/24
  metrics:
    ipam:
      driver: default
      config:
        - subnet: 10.53.2.0/24
